import './globals.css'
import { Inter } from 'next/font/google'
import { AuthContextProvider } from './Login/authContext'

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Pool Party',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
